
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "7040:7040"
    depends_on:
      - postgres
    env_file:
      - config.env
    networks:
      - appnet

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - config.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 3
    networks:
      - appnet

volumes:
  postgres_data:

networks:
  appnet:
    driver: bridge
