
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    
       # app:
  #   build: ./cmd/main
  #   ports:
  #     - "8080:8080"
  #   depends_on: 
  #     - postgres  